### ISSUE TITLE
As a player, I would want to see a main menu with all the options

### ISSUE THREAD

**Issue by ChristopherTeyWeixian** [ChristopherTeyWeixian/SimpCity#1]

**Comment by ChristopherTeyWeixian** [comment]
Hi Jing Xiang, is it ok for this feature to be done by tomorrow(3/12)?

**Comment by Creldra** [comment]
okay

**Comment by Creldra** [comment]
menu function for both main menu and game menu created, ready for testing

**Comment by ChristopherTeyWeixian** [comment]
thank you

**Comment by ChristopherTeyWeixian** [comment]
We can now proceed with the testing phase ben, can we get this done by 7 dec?

**Comment by teyzx123** [comment]
ok

**Comment by teyzx123** [comment]
Sorry click on the wrong button

**Comment by teyzx123** [comment]
Manuel testing is done

**Comment by Keithpek** [comment]
Review is done, looks okay

**Comment by ChristopherTeyWeixian** [comment]
Same goes for me.  looking good
