### ISSUE TITLE
We want to save the game

### ISSUE THREAD

**Issue by ChristopherTeyWeixian** [ChristopherTeyWeixian/SimpCity#10]

**Comment by ChristopherTeyWeixian** [comment]
This is one of the features for increment 2

**Comment by Keithpek** [comment]
Hi @Creldra, can you get this feature done in 2 days?

**Comment by Creldra** [comment]
Yes

**Comment by Creldra** [comment]
@Keithpek I have completed the Save Game function, please review

**Comment by Keithpek** [comment]
Looks okay to me, thank you for the work @Creldra

**Comment by Creldra** [comment]
@Keithpek Sorry, after checking the codes, it seems that I forgot to include the turns and buildings left to be saved as well, please re-assign me back to the issue.

**Comment by Keithpek** [comment]
Okay, please work on it

**Comment by Creldra** [comment]
@Keithpek I have just completed the fixed. Please review

**Comment by Keithpek** [comment]
I found a minor print error and will be commenting that out. Overall, looks okay. Thanks again @Creldra

**Comment by Keithpek** [comment]
@ChristopherTeyWeixian you can perform testing now

**Comment by ChristopherTeyWeixian** [comment]
ok

**Comment by ChristopherTeyWeixian** [comment]
"Game saved!" is not displayed after entering choice 5. @Keithpek

**Comment by Keithpek** [comment]
Okay will look into it

**Comment by Keithpek** [comment]
Okay I fixed the errors, please help to check @ChristopherTeyWeixian

**Comment by ChristopherTeyWeixian** [comment]
Done with the testing and test script. @teyzx123 please check

**Comment by teyzx123** [comment]
ok I will check now

**Comment by teyzx123** [comment]
alright it looks fine

**Comment by Keithpek** [comment]
Alright thanks all

**Comment by teyzx123** [comment]
please review  @Keithpek @ChristopherTeyWeixian

**Comment by ChristopherTeyWeixian** [comment]
Review is done, looking good

**Comment by Keithpek** [comment]
Looks good to me

**Comment by Keithpek** [comment]
Automation did not set this issue as done
