### ISSUE TITLE
We want the option to exit to main menu

### ISSUE THREAD

**Issue by ChristopherTeyWeixian** [ChristopherTeyWeixian/SimpCity#11]

**Comment by ChristopherTeyWeixian** [comment]
This is one of the features for increment 2

**Comment by Keithpek** [comment]
This feature was already developed during increment 1 @ChristopherTeyWeixian

**Comment by ChristopherTeyWeixian** [comment]
why was I not informed about it and why was this not tagged?

**Comment by ChristopherTeyWeixian** [comment]
How can we go about this now?

**Comment by Keithpek** [comment]
Sorry, it was an oversight on my part along with @Creldra not tagging the issue. Since this was done in increment 1, we will treat this issue as done and ready for testing during this current increment.

**Comment by ChristopherTeyWeixian** [comment]
ok

**Comment by Keithpek** [comment]
@teyzx123 You can perform testing now

**Comment by teyzx123** [comment]
ok

**Comment by teyzx123** [comment]
Im done with testing

**Comment by Keithpek** [comment]
Okay thank you

**Comment by teyzx123** [comment]
please review  @Keithpek @ChristopherTeyWeixian

**Comment by ChristopherTeyWeixian** [comment]
Review is done, looking good

**Comment by Keithpek** [comment]
Looks good to me

**Comment by Keithpek** [comment]
Automation did not set this issue as done
