### ISSUE TITLE
Fix yml file error

### ISSUE THREAD

**Issue by ChristopherTeyWeixian** [ChristopherTeyWeixian/SimpCity#13]

**Comment by ChristopherTeyWeixian** [comment]
Had found the error to why yml file is not working as intended. 
It had this error "  FileNotFoundError: [Errno 2] No such file or directory " and it shows that the linking to file directory needs to have the normal slash ("/") instead of the backward slash ("\").

**Comment by ChristopherTeyWeixian** [comment]
Can you fix it? @Keithpek

**Comment by Keithpek** [comment]
Okay will do

**Comment by Keithpek** [comment]
I have finished working on this issue, it is ready for testing

**Comment by Keithpek** [comment]
@teyzx123 Can you help to test this out?

**Comment by teyzx123** [comment]
ok

**Comment by teyzx123** [comment]
testing is done, error is fixed

**Comment by teyzx123** [comment]
please review  @Keithpek @ChristopherTeyWeixian

**Comment by ChristopherTeyWeixian** [comment]
Review is done, looking good

**Comment by Keithpek** [comment]
Looks good to me

**Comment by Keithpek** [comment]
Automation did not set this issue as done
