### ISSUE TITLE
We want the game to end after all the slots have been taken.

### ISSUE THREAD

**Issue by ChristopherTeyWeixian** [ChristopherTeyWeixian/SimpCity#16]

**Comment by ChristopherTeyWeixian** [comment]
This is one of the features for increment 3

**Comment by Keithpek** [comment]
@Creldra can you complete this feature by 11 Jan?

**Comment by Creldra** [comment]
Yes.

**Comment by Creldra** [comment]
@Keithpek I have just completed the end game method, please review.

**Comment by Keithpek** [comment]
Looks good, thanks for the work @Creldra

**Comment by teyzx123** [comment]
![image](https://user-images.githubusercontent.com/78276196/152645018-77fc5ae1-bf10-4d81-a775-697cc781fe70.png)
@Creldra please resolve this issue, error pops up after I place in the building in the last remaining slot

**Comment by Creldra** [comment]
@teyzx123 Fixed the issue, please check.

**Comment by teyzx123** [comment]
Looks good

**Comment by teyzx123** [comment]
@Keithpek @ChristopherTeyWeixian please review

**Comment by ChristopherTeyWeixian** [comment]
look good to me

**Comment by Keithpek** [comment]
Looks good to me too

**Comment by Keithpek** [comment]
Automation did not close issue and set as done
