### ISSUE TITLE
We want the game to always show remaining buildings so that it always display without having to choose the option to display them

### ISSUE THREAD

**Issue by ChristopherTeyWeixian** [ChristopherTeyWeixian/SimpCity#17]

**Comment by ChristopherTeyWeixian** [comment]
This is one of the features for increment 3

**Comment by ChristopherTeyWeixian** [comment]
Modified to include details. @Keithpek

**Comment by Keithpek** [comment]
noted

**Comment by Keithpek** [comment]
@Creldra can you complete this feature by today?

**Comment by Creldra** [comment]
alright

**Comment by Creldra** [comment]
@Keithpek Is it possible to extend the feature completed deadline to tomorrow, 14/01, as seen in the development timeline, tomorrow has no new features coming in as I may need more time to finish up both features.

**Comment by Keithpek** [comment]
Sure

**Comment by Creldra** [comment]
@Keithpek I have completed the always show remaining building, please review.

**Comment by Keithpek** [comment]
Looks good, thanks @Creldra

**Comment by ChristopherTeyWeixian** [comment]
@teyzx123 As discussed earlier, i will be assisting to test this issue

**Comment by teyzx123** [comment]
ok noted

**Comment by ChristopherTeyWeixian** [comment]
I have done testing, please check. @teyzx123

**Comment by teyzx123** [comment]
ok done

**Comment by teyzx123** [comment]
@Keithpek @ChristopherTeyWeixian please review

**Comment by Keithpek** [comment]
Looks good to me

**Comment by ChristopherTeyWeixian** [comment]
looks good

**Comment by Keithpek** [comment]
Automation did not close issue and set as done
