### ISSUE TITLE
We want the addition of new buildings to the game so that the game will play out differently with these additions

### ISSUE THREAD

**Issue by ChristopherTeyWeixian** [ChristopherTeyWeixian/SimpCity#18]

**Comment by ChristopherTeyWeixian** [comment]
This is one of the features for increment 3

**Comment by ChristopherTeyWeixian** [comment]
Modified to include details. @Keithpek

**Comment by Keithpek** [comment]
noted

**Comment by Keithpek** [comment]
@Creldra can you complete this feature by today?

**Comment by Creldra** [comment]
alright

**Comment by Creldra** [comment]
@Keithpek Is it possible to extend the feature completed deadline to tomorrow, 14/01, as seen in the development timeline, tomorrow has no new features coming in as I may need more time to finish up both features.

**Comment by Keithpek** [comment]
Sure

**Comment by Creldra** [comment]
@Keithpek I have completed the new buildings to be implemented into the game, please review.

**Comment by Keithpek** [comment]
Looks good, thanks @Creldra

**Comment by teyzx123** [comment]
![image](https://user-images.githubusercontent.com/78276196/152646770-4773d166-b5a0-4c62-8409-0b6112f401ff.png)
3 issues I found, 

- I cannot enable or disable the "shop" building
- When I enter option outside the menu, It will crash the game(8,9,10,11...)
- Cannot exit out of option, so "0" does nothing

**Comment by Keithpek** [comment]
Noted, will fix the issues

**Comment by Keithpek** [comment]
@teyzx123 Please do check again

**Comment by teyzx123** [comment]
ok done

**Comment by teyzx123** [comment]
@Keithpek @ChristopherTeyWeixian please review

**Comment by ChristopherTeyWeixian** [comment]
Look good to me

**Comment by Keithpek** [comment]
Looks good to me too

**Comment by Keithpek** [comment]
Automation did not close issue and set as done
