### ISSUE TITLE
We want to choose the building pool so that building choices can be chosen according to our preference

### ISSUE THREAD

**Issue by ChristopherTeyWeixian** [ChristopherTeyWeixian/SimpCity#19]

**Comment by ChristopherTeyWeixian** [comment]
This is one of the features for increment 3

**Comment by ChristopherTeyWeixian** [comment]
Modified to include details. @Keithpek

**Comment by Keithpek** [comment]
noted

**Comment by Keithpek** [comment]
@Creldra can you complete this feature by 17th Jan?

**Comment by Creldra** [comment]
Alright

**Comment by Creldra** [comment]
@Keithpek I have completed it, please review and confirm. thank you.

**Comment by Keithpek** [comment]
Looks good, thanks @Creldra

**Comment by teyzx123** [comment]
done with testing

**Comment by teyzx123** [comment]
@Keithpek @ChristopherTeyWeixian please review

**Comment by ChristopherTeyWeixian** [comment]
look good to me

**Comment by Keithpek** [comment]
Looks good to me too

**Comment by Keithpek** [comment]
Automation did not close issue and set as done
