### ISSUE TITLE
As a player, I would want to start a new game

### ISSUE THREAD

**Issue by ChristopherTeyWeixian** [ChristopherTeyWeixian/SimpCity#2]

**Comment by ChristopherTeyWeixian** [comment]
Hi Jing Xiang, is it ok for this feature to be done by 5 Dec?

**Comment by Creldra** [comment]
okay

**Comment by Creldra** [comment]
new game function created, ready for testing

**Comment by ChristopherTeyWeixian** [comment]
We can now proceed with the testing phase ben, can we get this done by 7 dec?

**Comment by teyzx123** [comment]
ok

**Comment by teyzx123** [comment]
@Creldra You have forgotten to include a return value for the new_board function
@ChristopherTeyWeixian Mind assigning back Jing Xiang to work on this, thank you very much

**Comment by ChristopherTeyWeixian** [comment]
Ok noted.

**Comment by Creldra** [comment]
understood, I will work on it.

**Comment by Creldra** [comment]
@ChristopherTeyWeixian @teyzx123 Return Value has been included, ready to be check

**Comment by ChristopherTeyWeixian** [comment]
Thank you

**Comment by teyzx123** [comment]
ok thanks, I will go look at it

**Comment by teyzx123** [comment]
Manual testing is done, the test script is also ready. I will begin continuous integration with Christopher

**Comment by Keithpek** [comment]
Review is done, looks okay

**Comment by ChristopherTeyWeixian** [comment]
Same goes for me.  looking good
