### ISSUE TITLE
We would want to see our current score so that we know what is our score at the end of the game

### ISSUE THREAD

**Issue by ChristopherTeyWeixian** [ChristopherTeyWeixian/SimpCity#20]

**Comment by ChristopherTeyWeixian** [comment]
This is one of the features for increment 3

**Comment by ChristopherTeyWeixian** [comment]
Modified to include details. @Keithpek

**Comment by Keithpek** [comment]
noted

**Comment by Keithpek** [comment]
I will now work on this feature and complete it by 22th Jan

**Comment by Keithpek** [comment]
@Creldra can you help to takeover and finish this feature?

**Comment by Creldra** [comment]
alright, I will try my best and see if I can complete it

**Comment by Creldra** [comment]
@Keithpek I have completed the function, please check and review

**Comment by Keithpek** [comment]
@Creldra I found an error for PRK calculation, can you look into it?

**Comment by Creldra** [comment]
Understood, will look into it.

**Comment by Creldra** [comment]
@Keithpek Fixed and Updated the Calculate Score

**Comment by Keithpek** [comment]
Okay thank you for your work @Creldra

**Comment by ChristopherTeyWeixian** [comment]
@teyzx123 As discussed earlier, i will be assisting to test this issue

**Comment by teyzx123** [comment]
ok noted

**Comment by ChristopherTeyWeixian** [comment]
![image](https://user-images.githubusercontent.com/64050082/152643886-44180770-0461-49b6-b90d-fac47973348b.png)
This is the error i got when i end the game and is expecting to see my score. It occur at the calculation for house

**Comment by ChristopherTeyWeixian** [comment]
@Keithpek

**Comment by Keithpek** [comment]
Noted, @Creldra will you be able to fix this issue?

**Comment by Creldra** [comment]
Noted, will do so.

**Comment by Creldra** [comment]
@Keithpek @ChristopherTeyWeixian The Issue has been fixed, please check

**Comment by ChristopherTeyWeixian** [comment]
ok

**Comment by ChristopherTeyWeixian** [comment]
Done testing, please check. @teyzx123

**Comment by teyzx123** [comment]
ok noted

**Comment by teyzx123** [comment]
@Keithpek @ChristopherTeyWeixian please review

**Comment by Keithpek** [comment]
Looks good to me

**Comment by ChristopherTeyWeixian** [comment]
looks good to me

**Comment by Keithpek** [comment]
Automation did not close issue and set as done
