### ISSUE TITLE
We want the game to show high score of the top 10 so that it displays users with the high scores to mark as game history

### ISSUE THREAD

**Issue by ChristopherTeyWeixian** [ChristopherTeyWeixian/SimpCity#21]

**Comment by ChristopherTeyWeixian** [comment]
This is one of the features for increment 3

**Comment by ChristopherTeyWeixian** [comment]
Modified to include details. @Keithpek

**Comment by Keithpek** [comment]
noted

**Comment by Keithpek** [comment]
I will now start on this feature, aiming to complete it within 3 days

**Comment by Keithpek** [comment]
I will put this feature on hold.

**Comment by Keithpek** [comment]
I will resume development for this feature

**Comment by Keithpek** [comment]
@ChristopherTeyWeixian You can start testing this issue

**Comment by ChristopherTeyWeixian** [comment]
noted

**Comment by ChristopherTeyWeixian** [comment]
Done with testing,please check. @teyzx123

**Comment by teyzx123** [comment]
ok noted

**Comment by teyzx123** [comment]
@Keithpek @ChristopherTeyWeixian please review

**Comment by Keithpek** [comment]
Looks good to me

**Comment by ChristopherTeyWeixian** [comment]
looks good

**Comment by Keithpek** [comment]
Automation did not close issue and set as done
