### ISSUE TITLE
Modification of codebase

### ISSUE THREAD

**Issue by Keithpek** [ChristopherTeyWeixian/SimpCity#22]

**Comment by Keithpek** [comment]
@ChristopherTeyWeixian @Keithpek @Creldra @teyzx123 We will put development and testing on hold. We will be modifying the current codebase to make it more efficient.

**Comment by ChristopherTeyWeixian** [comment]
As discussed in the team call earlier, lets proceed with this.

**Comment by teyzx123** [comment]
noted

**Comment by Creldra** [comment]
alright, understood.

**Comment by Keithpek** [comment]
@teyzx123 you can start testing now with the addition of our modifications

**Comment by teyzx123** [comment]
ok done

**Comment by teyzx123** [comment]
@Keithpek @ChristopherTeyWeixian please review

**Comment by Keithpek** [comment]
Looks good to me

**Comment by ChristopherTeyWeixian** [comment]
looks good

**Comment by Keithpek** [comment]
Automation did not close issue and set as done
