### ISSUE TITLE
Splitting of increment 3 into increment 3.1 and 3.2 due to time constraint.

### ISSUE THREAD

**Issue by ChristopherTeyWeixian** [ChristopherTeyWeixian/SimpCity#23]

**Comment by ChristopherTeyWeixian** [comment]
@ChristopherTeyWeixian @Keithpek @Creldra @teyzx123 Due to time constraint and to meet deadline, we will be splitting increment 3 into increment 3.1 and 3.2 due to time constraint. 

Increment 3.1 will be comprising of issues #16 #17 #18 #19 #20 #22 
Increment 3.2 will be comprising of issue #21 

@teyzx123  u can start with the testing of increment 3.1 and I will be assisting you in some issues.

**Comment by teyzx123** [comment]
noted

**Comment by Keithpek** [comment]
noted

**Comment by Lowkh** [comment]
Is the test done /passed/ or what happened such that the issue is directly moved from backlog to done?

**Comment by ChristopherTeyWeixian** [comment]
This issue is solely for informing the team about the splitting of increment 3 into increment 3.1 and 3.2.  @Lowkh

**Comment by ChristopherTeyWeixian** [comment]
the necessary people needed to be informed are aware about this change. Teyzx123 to start testing and keith who is in charge of developing issue 21
