### ISSUE TITLE
As a player, I would want to exit the game

### ISSUE THREAD

**Issue by ChristopherTeyWeixian** [ChristopherTeyWeixian/SimpCity#3]

**Comment by ChristopherTeyWeixian** [comment]
Hi Jing Xiang, is it ok for this feature to be done by tomorrow(3/12)?

**Comment by Creldra** [comment]
okay

**Comment by Creldra** [comment]
Exit function created, ready for testing

**Comment by ChristopherTeyWeixian** [comment]
We can now proceed with the testing phase ben, can we get this done by 7 dec?

**Comment by teyzx123** [comment]
ok

**Comment by teyzx123** [comment]
Manual testing is done

**Comment by Keithpek** [comment]
Review is done, looks okay

**Comment by ChristopherTeyWeixian** [comment]
Same goes for me.  looking good

**Comment by Lowkh** [comment]
> Review is done, looks okay

Review is done based on what evidence from the QA. No result screenshot is available. Is it somewhere else in excel? Please include in the report.
