### ISSUE TITLE
As a player, I would want to build buildings in the game

### ISSUE THREAD

**Issue by ChristopherTeyWeixian** [ChristopherTeyWeixian/SimpCity#5]

**Comment by ChristopherTeyWeixian** [comment]
clicked the wrong milestone

**Comment by ChristopherTeyWeixian** [comment]
can this be done by 16 dec?

**Comment by Keithpek** [comment]
Okay

**Comment by Keithpek** [comment]
I will be taking more time to combine this feature with the feature to choose where to build the buildings

**Comment by ChristopherTeyWeixian** [comment]
will this be done together with the another feature?

**Comment by Keithpek** [comment]
Yep

**Comment by ChristopherTeyWeixian** [comment]
noted

**Comment by Keithpek** [comment]
New game feature created, ready for testing.

**Comment by ChristopherTeyWeixian** [comment]
Thank you

**Comment by Keithpek** [comment]
Moving feature #5 back to in progress, function specified in this feature will be modified during the implementation of feature #9.

**Comment by Keithpek** [comment]
@ChristopherTeyWeixian Thanks again for helping.

**Comment by Keithpek** [comment]
@teyzx123 You can perform testing now

**Comment by teyzx123** [comment]
ok

**Comment by teyzx123** [comment]
@Keithpek
This are the errors I found during testing
input for building placement is outside of the method, cannot test input when the input is inside the method.
Cannot directly enter location example A1 as a parameter in the testing script as it is not the actual coordinate for code testing

**Comment by Keithpek** [comment]
Okay, I will work on it

**Comment by Keithpek** [comment]
Okay I fixed the errors, please help to check @teyzx123

**Comment by teyzx123** [comment]
Done with testing and testscript

**Comment by Keithpek** [comment]
Okay thank you

**Comment by teyzx123** [comment]
please review  @Keithpek @ChristopherTeyWeixian

**Comment by ChristopherTeyWeixian** [comment]
Review is done, looking good

**Comment by Keithpek** [comment]
Looks good to me
