### ISSUE TITLE
As a player, I would want the choice to choose where to build my building.

### ISSUE THREAD

**Issue by ChristopherTeyWeixian** [ChristopherTeyWeixian/SimpCity#6]

**Comment by ChristopherTeyWeixian** [comment]
Can this feature be done by 18 dec?

**Comment by Keithpek** [comment]
Okay

**Comment by Keithpek** [comment]
I will be combining the feature to place buildings, with this feature

**Comment by ChristopherTeyWeixian** [comment]
noted

**Comment by Keithpek** [comment]
New game feature created, ready for testing.

**Comment by ChristopherTeyWeixian** [comment]
thank you

**Comment by Keithpek** [comment]
@teyzx123 You can perform testing now

**Comment by teyzx123** [comment]
ok

**Comment by Keithpek** [comment]
@teyzx123 will be performing testing instead of having both of you do it.    @ChristopherTeyWeixian

**Comment by teyzx123** [comment]
@Keithpek 
This are the issues I found during testing
invalid inputs cause error(eg. BB, 1A,AB) 
user can still choose building option that does not have any copies left 
input for building placement is outside of the method, cannot test input when the input is inside the method
Cannot directly enter location example A1 as a parameter in the testing script as it is not the actual coordinate for code testing

**Comment by Keithpek** [comment]
Okay, I will work on it

**Comment by Keithpek** [comment]
Okay I fixed the errors, please help to check @teyzx123

**Comment by teyzx123** [comment]
Done with testing and testscript

**Comment by Keithpek** [comment]
Okay thank you

**Comment by teyzx123** [comment]
please review  @Keithpek @ChristopherTeyWeixian

**Comment by ChristopherTeyWeixian** [comment]
Review is done, looking good

**Comment by Keithpek** [comment]
Looks good to me

**Comment by Keithpek** [comment]
Automation did not set this issue as done
