### ISSUE TITLE
As a player, I would not want the buildings to overlap with existing building

### ISSUE THREAD

**Issue by ChristopherTeyWeixian** [ChristopherTeyWeixian/SimpCity#7]

**Comment by ChristopherTeyWeixian** [comment]
Can this be done by 22 dec?

**Comment by Keithpek** [comment]
Okay

**Comment by Keithpek** [comment]
New game feature created, ready for testing.

**Comment by ChristopherTeyWeixian** [comment]
thank you very much

**Comment by Keithpek** [comment]
@teyzx123 You can perform testing now

**Comment by teyzx123** [comment]
ok

**Comment by Keithpek** [comment]
@teyzx123 will be performing testing instead of having both of you do it.    @ChristopherTeyWeixian

**Comment by teyzx123** [comment]
@Keithpek
issues I found during testing
input for building placement is outside of the method, cannot test input when the input is inside the method
Cannot directly enter location example A1 as a parameter in the testing script as it is not the actual coordinate for code testing

**Comment by Keithpek** [comment]
Okay, I will work on it

**Comment by Keithpek** [comment]
Okay I fixed the errors, please help to check @teyzx123

**Comment by teyzx123** [comment]
Done with testing and testscript

**Comment by Keithpek** [comment]
Okay thank you

**Comment by teyzx123** [comment]
please review  @Keithpek @ChristopherTeyWeixian

**Comment by ChristopherTeyWeixian** [comment]
Review is done, looking good

**Comment by Keithpek** [comment]
Looks good to me

**Comment by Keithpek** [comment]
Automation did not set this issue as done
