### ISSUE TITLE
We want to see the remaining type of buildings that can be built

### ISSUE THREAD

**Issue by ChristopherTeyWeixian** [ChristopherTeyWeixian/SimpCity#8]

**Comment by ChristopherTeyWeixian** [comment]
This is one of the features for increment 2

**Comment by Keithpek** [comment]
I will now start on this feature, aiming to complete it in 2 days.

**Comment by Keithpek** [comment]
I have finished working on this feature. It is ready for testing.

**Comment by Keithpek** [comment]
@teyzx123 You can perform testing now

**Comment by teyzx123** [comment]
ok

**Comment by teyzx123** [comment]
Done with testing

**Comment by Keithpek** [comment]
Okay thank you

**Comment by teyzx123** [comment]
please review  @Keithpek @ChristopherTeyWeixian

**Comment by ChristopherTeyWeixian** [comment]
Review is done, looking good

**Comment by Keithpek** [comment]
Looks good to me

**Comment by Keithpek** [comment]
Automation did not set this issue as done
