### ISSUE TITLE
We want to have multiple building options when playing the game

### ISSUE THREAD

**Issue by ChristopherTeyWeixian** [ChristopherTeyWeixian/SimpCity#9]

**Comment by ChristopherTeyWeixian** [comment]
This is one of the features for increment 2

**Comment by Keithpek** [comment]
I will now start on this feature, and complete it by 25 Dec

**Comment by Keithpek** [comment]
Sorry, I need more time to work on this feature

**Comment by Keithpek** [comment]
Currently I have developed the randomizing of building options, as well as reformatted the place building format. I need help in placing the chosen building.

**Comment by Keithpek** [comment]
Is @Creldra or @ChristopherTeyWeixian able to help out on this?

**Comment by ChristopherTeyWeixian** [comment]
I can help out

**Comment by Keithpek** [comment]
Okay thank you @ChristopherTeyWeixian

**Comment by Keithpek** [comment]
Please tag issue #5 alongside issue #9

**Comment by ChristopherTeyWeixian** [comment]
Issue of placing the chosen building has been fixed. Please check @Keithpek .

**Comment by Keithpek** [comment]
Looks good to me. Thanks for the help.

**Comment by Keithpek** [comment]
@teyzx123 You can perform testing now

**Comment by teyzx123** [comment]
ok

**Comment by teyzx123** [comment]
Done with testing and testscript

**Comment by Keithpek** [comment]
Okay thank you

**Comment by teyzx123** [comment]
please review  @Keithpek @ChristopherTeyWeixian

**Comment by ChristopherTeyWeixian** [comment]
Review is done, looking good

**Comment by Keithpek** [comment]
Looks good to me

**Comment by Keithpek** [comment]
Automation did not set this issue as done
